global:
  scrape_interval: 5s  # ตั้งค่าให้ Scrape ทุก 5 วินาที

scrape_configs:
  - job_name: "backend-camera"
    static_configs:
      - targets: ["backend-camera:8000"]

  - job_name: "web_server_1"
    static_configs:
      - targets: ["web_server_1:9100"]

  - job_name: "web_server_2"
    static_configs:
      - targets: ["web_server_2:9100"]

  - job_name: "web_server_3"
    static_configs:
      - targets: ["web_server_3:9100"]
